### ISSUE TITLE
Embeds need to be styled

### ISSUE THREAD

**Issue by bit-map** [MasterDalK/kktCSS#25]
Currently, embeds (which work for YouTube video links and Twitter tweet links and can be seen for a katsu's detailed view) look like this:
![chrome_2017-04-23_16-58-44](https://cloud.githubusercontent.com/assets/6811760/25317420/5d3388bc-2846-11e7-8854-3d687d125c1a.png)

After some quick tests, I think having the embed card look like this gave the best results:
![chrome_2017-04-23_17-04-04](https://cloud.githubusercontent.com/assets/6811760/25317459/fc9bdf3a-2846-11e7-82d0-a9090d89d9ce.png)
But then it raises the question of how it should look on hover.

Alternatively, I think something like this could look good as well:
![chrome_2017-04-23_17-09-55](https://cloud.githubusercontent.com/assets/6811760/25317499/b9c65a68-2847-11e7-9cd3-8ee02c849dcf.png)
And in this case, the on hover color could be the alternative pink that we have for the reply indicator in the drawer, giving it the same green/pink vibe as links in katsus, which might fit the embed, as a clickable element to outside content, better design-wise.

Anyway, just wanted to get opinions from @MasterDalK or other contributors before I put everything together in a PR.

**Comment by MasterDalK** [comment]
I like the bubble on bubble, the green seems too flat to have in, also helps in case they ever have quote RTs like twitter it'll be consistent

**Comment by bit-map** [comment]
Yeah, I don't think the flat green worked too well. What do you think the behavior when you hover over the embed should be, then? Currently, the background goes dark grey, but that doesn't really work here.

**Comment by AbelToy** [comment]
For the onhover, maybe just make the border a darker color, like Twitter does?

**Comment by MasterDalK** [comment]
Sounds good to me!

**Comment by bit-map** [comment]
I don't think we ever defined a darker variant for that golden color so I just picked something from a color picker for the time being:
![chrome_2017-04-24_19-06-14](https://cloud.githubusercontent.com/assets/6811760/25362402/a852f0ea-2921-11e7-9f13-c7e799028555.png)

Exact color aside, I can't say I'm in love with it because it's not a model we see elsewhere (eg. when you hover over the part of a toot that will open up the detailed status page on the column, the outline does not change). Let me throw up a PR though, so that everyone can comment directly on the changes.
