### ISSUE TITLE
Two-factor authentication recovery codes color

### ISSUE THREAD

**Issue by AbelToy** [MasterDalK/kktCSS#36]
When enabling two-factor authentication in your account, the last step presents you with a list of recovery codes you may want to store just in case.

Unfortunately, those codes are white text over the yellowish background, making them very hard to see. I can't attach a screenshot because of security reasons, but it should be easy to reproduce, even if a pain in the ass.

**Comment by MasterDalK** [comment]
I'll take a look tonight, thanks for the heads up!
