### ISSUE TITLE
In iOS9, column settings and Getting Started are partially hidden by following elements

### ISSUE THREAD

**Issue by unarist** [MasterDalK/kktCSS#51]
This is an upstream issue, but it will be noticeable with kktCSS because we have translucent background for following elements.

![img_4094](https://cloud.githubusercontent.com/assets/705555/25566462/f11007e0-2e13-11e7-8d79-ee96f283668f.jpg)

This problem seems a flexbox bug on iOS9:
https://github.com/philipwalton/flexbugs#1-minimum-content-sizing-of-flex-items-not-honored

and can be avoid with `flex-shrink: 0` on that overlapped element, probably.

**Comment by MasterDalK** [comment]
Let me know when you're able to test some possible fixes. I don't have an apple device, let alone iOS9 on one, so I want to make sure it's good before pushing anything.
