### ISSUE TITLE
[RFC] Changing inline SVG format

### ISSUE THREAD

**Issue by bit-map** [MasterDalK/kktCSS#54]
Currently, we use inline SVGs as background images, which we have encoded in base64. This decision was made after a lot of headaches trying to get SVGs to work in Firefox.

I think we could use the method here to go back to having human-readable inline SVGs while still keeping browser compatibility: https://codepen.io/tigt/post/optimizing-svgs-in-data-uris
This seems like it would make finding potential SVG bugs and keeping track of changes easier.

Alternatively, focusing on site integration, we could just have separate SVG files instead of inline, although that would also make things a little more difficult to test with, say, Dropbox + JavaScript bookmarklets.

Anyway, would like to hear some thoughts before moving forward (or keeping our current format).

**Comment by MasterDalK** [comment]
I think moving back to human-readable SVGs would be dope, if they work everywhere. I'll give it a shot after 9.0 releases, since it _is_ a mainly site integration based change.
