### ISSUE TITLE
[iOS9+1.3.x] cannot scroll on drawer and profile

### ISSUE THREAD

**Issue by unarist** [MasterDalK/kktCSS#56]
## Problem

Reproduce steps:

- Visit some timeline (home or public) filled toots
- Visit drawer (/web/statuses/new), open privacy options, and scroll down (you need to slide up on privacy options)
- or, visit someone's profile (/web/accounts/xxx), and scroll down

This problem only occurs on Mastodon 1.3.x, and this may not  occur on iOS10.

Also it can be avoid by touching  somewhere before scrolling if you didn't apply kktCSS.

## Consideration & Workaround

I've found below workarounds for this issue, at least:

- `.mastodon-column-container { z-index: -1 }` (or less)
- `.mastodon-column-container[aria-hidden="true"] { display: none }`

`.mastodon-column-container` [was introduced at Mastodon 1.3](https://github.com/tootsuite/mastodon/pull/2271). On switching column, it will be `visibility: hidden` instead of replacing DOM elements (unmounting on React).

It will be absolutely positioned only while it's hidden, so we can use `z-index` patch safely without worrying `aria-hidden` state. Also these workarounds wouldn't have bad effects for other components I think.

I think this should be fixed on V9 release because it's serious problem for iOS9 users, although  still I don't know what root issue (maybe WebKit bug?) is and how it causes this problem...

**Comment by MasterDalK** [comment]
It is definitely some issue with iOS9 itself. This fix doesn't mess anything up on desktop.

Does this fix let us remove the `flex-shrink:0` or is that still needed?

**Comment by unarist** [comment]
`flex-shrink:0` is a different problem, so it is still needed.

btw, I've written wrong `z-index` value on my first post. It should be less than 0, actually. (and edited)

**Comment by MasterDalK** [comment]
`z-index: -1` makes all columns disappear, so I think we need to do
`.mastodon-column-container[aria-hidden="true"] { z-index: -1; display: none; }` ?

**Comment by unarist** [comment]
You need only which `z-index: -1` or `display: none`.

But `z-index: -1` doesn't do that on iOS9...sigh.
