### ISSUE TITLE
Remote follow confirmation page

### ISSUE THREAD

**Issue by unarist** [MasterDalK/kktCSS#64]
I forgot about `.follow-prompt` part on #42.

1. Visit an user page on another instance, and click "REMOTE FOLLOW"
2. Enter your kkt account
3. You will be redirected to confirmation page like this:

https://kirakiratter.com/authorize_follow?acct=acct%3Apixiv%40pawoo.net

![image](https://cloud.githubusercontent.com/assets/705555/26036575/0a5d9106-391b-11e7-9d09-f37686778fc6.png)

and my first idea is...our usual design:

![image](https://cloud.githubusercontent.com/assets/705555/26036620/d0350864-391b-11e7-82b2-96e4c5f1820f.png)

**Comment by MasterDalK** [comment]
I think making the user display name pink (instead of black) would be good too, since that is how it is everywhere else

**Comment by unarist** [comment]
OK, I have sent a PR with that fix.
