### ISSUE TITLE
Opening dropdown on the status in detailed status view causes weird spacing

### ISSUE THREAD

**Issue by unarist** [MasterDalK/kktCSS#70]
i.e. /web/statuses/...

![image](https://cloud.githubusercontent.com/assets/705555/26284672/f73bd036-3e7b-11e7-9b7a-5b1dc8f57015.png)
![image](https://cloud.githubusercontent.com/assets/705555/26284674/073f68b2-3e7c-11e7-919a-91f3fbaf0b44.png)

Since the dropdown has `position: relative`, the width of the dropdown effects `detailed-status__button`  which is their parent element.

**Comment by bit-map** [comment]
We had done a bunch of stuff with dropdowns back in mid-April to fix the fact that the upstream version at the time:
- truncated the text, which was pretty much unusable in Japanese
- had issues with positioning dropdowns for very long threads in detailed status view.

As far as I can tell, both of those issues have been fixed upstream as of 1.4 so I think if we get rid of our custom CSS related to dropdown stuff it should fix everythin―
![image](https://cloud.githubusercontent.com/assets/6811760/26285180/b7223db8-3e18-11e7-9bab-9b93af7f6006.png)

...Well, almost everything (that one's a bug in 1.4.0.2 upstream)

**Comment by MasterDalK** [comment]
Changes in 10.0 solve this issue.
