### ISSUE TITLE
/settings heading should have different style than menus

### ISSUE THREAD

**Issue by unarist** [MasterDalK/kktCSS#71]
|Original|kktCSS|
|---------|-------|
| ![image](https://cloud.githubusercontent.com/assets/705555/26297197/c71cfa10-3f0c-11e7-86a7-0892d3f3b5b5.png) | ![image](https://cloud.githubusercontent.com/assets/705555/26297163/b0d3e340-3f0c-11e7-8b3c-0e4087bb3291.png) |

I've set same background color for `.admin-wrapper .sidebar ul a.selected` and `.admin-wrapper .sidebar ul ul` before, but those are heading and its contents, so it should have different styles.

Upstream uses (slightly) different background-color. For another solution, my friend uses different padding for those.
https://mstdn.maud.io/@musashino205/2180562
https://github.com/musashino205/mastodon/commit/50ed91905b7a52f396cd8d822ae184d67a39658b

**Comment by MasterDalK** [comment]
I think the slightly different padding would be good!
