### ISSUE TITLE
Mention in the profile of remote user

### ISSUE THREAD

**Issue by unarist** [MasterDalK/kktCSS#73]
![image](https://user-images.githubusercontent.com/705555/26871307-b57dd61e-4bad-11e7-87a3-ab3a30f8ae5e.png)

We have colored whole of `@user` to pink, but it's not applied to the remote user's profile due to HTML structure difference.

- Local: `div.account__header__content > p > span.h-card > a.u-url.mention > span`
- Remote: `div.account__header__content > p > span.h-card > a > span`

Maybe this should be fixed on upstream, but this bug still exists on 1.4.1 at least.

**Comment by unarist** [comment]
Oh, this HTML difference also exists on the status content, but it seems to be already fixed for kktCSS.

I've fixed the difference at tootsuite/mastodon#3623, so we can ignore this if the next release is for 1.4.2 or later.

**Comment by MasterDalK** [comment]
Probably is going to be slated for early next month (and hopefully next release), been super busy this month unfortunately. But at least that means one less thing to take care of.
